### ISSUE TITLE
nmap-converter no such file

### ISSUE THREAD

**Issue by Leeyo000** [mrschyte/nmap-converter#12]
i've done pip install XlsxWriter and python-libnmap and when i try to convert my xml and enter the command ./nmap-converter.py xxxxxx.xml -o xxxxxx.xls it says nmap-converter.py: no file or folder of this type 

How do i install this ?

**Comment by mrschyte** [comment]
Hi Leeyo000,

I've tried a fresh checkout and it's working fine for me. Can you  provide the exact command and the terminal output when you're trying to run nmap-converter?

Thanks

**Comment by Leeyo000** [comment]
That was my mistake i forgot to download the nmap-converter.py, Working way better now thank you !
