### ISSUE TITLE
Mac-Address

### ISSUE THREAD

**Issue by dlaarschot** [mrschyte/nmap-converter#4]
Looking to modify your script to include Mac-addresses. Cant seem to find out if that variable has been defined? Any ideas. Thanks.

**Comment by mrschyte** [comment]
Hi! Does your NMap results include MAC addresses? If your report has the data, you can access the MAC address using host.mac from the script. I've created a small patch for you that you can try out: https://gist.github.com/mrschyte/9f965d4b2f4b5a3339b38b8105695376

**Comment by dlaarschot** [comment]
Thanks! Exactly what I was looking for, should have tried host.mac! Thanks again!

**Comment by dlaarschot** [comment]
So I've given it ago, 

code here - 

def generate_hosts(workbook, sheet, report):
    sheet.autofilter("A1:E1")
    sheet.freeze_panes(1, 0)

    hosts_header = ["Host", "IP", "MAC", "Status", "Services", "OS"]
    hosts_body = {"Host": lambda host: next(iter(host.hostnames), ""),
                  "IP": lambda host: host.address,
                  "MAC": lambda host: host.mac,
                  "Status": lambda host: host.status,
                  "Services": lambda host: len(host.services),
                  "OS": lambda host: os_class_string(host.os_class_probabilities())}

result is that the MAC address is presented as the IP address, for reference this is how its referred to in the XML.

<address addr="x.x.x.x" addrtype="ipv4"/>
<address addr="xx:xx:xx:xx:xx:xx" addrtype="mac" vendor="xxxx"/>

**Comment by dlaarschot** [comment]
Thanks working perfectly :)
